version: '2'
services:
  nginx_server:
    container_name: "nginx_server"
    image: jasonrivers/nginx-rtmp
    expose:
      - 1935
  stress:
    extends:
      file: ../common/docker-compose.yaml
      service: stress-test-client
    links:
      - nginx_server:rtmp_server
    command: [go-wrapper,
              run,
              -flv_file,
               /opt/video/earth.flv,
              -server, nginx_rtmp, -redis,
              "[redis db ip]:[rdis db port]"]
  cadvisor:
    extends:
      file: ../common/docker-compose.yaml
      service: cadvisor
  node-exporter:
    extends:
      file: ../common/docker-compose.yaml
      service: node-exporter
