version: '2'
services:
  nimble:
    container_name: "nimble"
    image: rjrivero/nimble
    environment:
      - WMSPANEL_USER=flexconstructor@gmail.com
      - WMSPANEL_PASS=OEMY7jtyb/I
    ports:
      - "1935:1935"
      - "8081:8081"
  stress:
    extends:
      file: ../common/docker-compose.yaml
      service: stress-test-client
    links:
      - nimble:rtmp_server
    command: [go-wrapper,
              run,
              -flv_file,
              /opt/video/earth.flv,
              -server, nimble, -redis,
              "[redis db ip]:[redis db port]"]
  cadvisor:
    extends:
      file: ../common/docker-compose.yaml
      service: cadvisor
  node-exporter:
    extends:
      file: ../common/docker-compose.yaml
      service: node-exporter
