version: '2'
services:
  wowza:
    container_name: "wowza"
    image: sameersbn/wowza:4.1.2-8
    environment:
      - WOWZA_ACCEPT_LICENSE=yes
      - WOWZA_KEY=[wowza dev key]
    ports:
      - "1935:1935"
      - "8086:8086"
      - "8087:8087"
      - "8088:8088"
  stress:
    extends:
      file: ../common/docker-compose.yaml
      service: stress-test-client
    links:
      - wowza:rtmp_server
    command: [go-wrapper,
              run,
              -flv_file,
              /opt/video/sample.flv,
              -server, wowza, -redis ,
              "[redis db ip]:[redis db port]"]
  cadvisor:
    extends:
      file: ../common/docker-compose.yaml
      service: cadvisor
  node-exporter:
    extends:
      file: ../common/docker-compose.yaml
      service: node-exporter
