version: '2'
services:
  red5:
    container_name: "red5"
    image: mondain/red5
    ports:
      - "1935:1935"
      - "5080:5080"
  stress:
    extends:
      file: ../common/docker-compose.yaml
      service: stress-test-client
    links:
      - red5:rtmp_server
    command: [go-wrapper,
              run,
              -flv_file,
               /opt/video/earth.flv,
              -server, red5, -redis ,
              "[redis db ip]:[redis db port]"]
  cadvisor:
    extends:
      file: ../common/docker-compose.yaml
      service: cadvisor
  node-exporter:
    extends:
      file: ../common/docker-compose.yaml
      service: node-exporter
